config {
  type: "view",
  schema: "dados_mestres",
  name: "logradouro",
  tags: ["logradouro"]
}

SELECT
    id_logradouro,
    nome,
    nome_parcial,
    nome_completo,
    id_trecho,
    id_situacao_trecho,
    situacao_trecho,
    id_tipo,
    tipo,
    id_bairro,
    inicio_numero_porta_par,
    final_numero_porta_par,
    inicio_numero_porta_impar,
    final_numero_porta_impar,
    hierarquia,
    id_chavegeo,
    geometry
FROM datario.dados_mestres.logradouro